syntax = "proto3";                          
package Northwind;                           
option csharp_namespace = "GrpcServiceDemo"; 

//ĐỊNH NGHĨA SERVICE (các hàm gọi từ xa)
service EmployeeCRUD {
  rpc SelectAll  (Empty)          returns (Employees);  // Lấy tất cả nhân viên
  rpc SelectByID (EmployeeFilter) returns (Employee);   // Lấy 1 nhân viên theo ID
  rpc Insert     (Employee)       returns (Empty);      // Thêm mới
  rpc Update     (Employee)       returns (Empty);      // Cập nhật
  rpc Delete     (EmployeeFilter) returns (Empty);      // Xóa
}

//ĐỊNH NGHĨA MESSAGE (dữ liệu gửi/nhận)
message Empty {                              // Message rỗng
}

message Employee {                           
  int32  employeeID = 1;                     // Số 1,2,3 là FIELD NUMBER (định danh khi mã hóa nhị phân)
  string firstName  = 2;                     
  string lastName   = 3;
}

message Employees {                          // Danh sách nhiều nhân viên
  repeated Employee items = 1;               
}

message EmployeeFilter {                     // Bộ lọc (để chọn/xóa theo ID)
  int32 employeeID = 1;
}